name: E2E Tests

on:
  push:
    branches: '**'
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.css'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'playwright.config.ts'
      - '.github/workflows/e2e.yml'
  pull_request:
    branches: '**'
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.css'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'playwright.config.ts'
      - '.github/workflows/e2e.yml'
  # Allow manual triggers with options
  workflow_dispatch:
    inputs:
      run_all_browsers:
        description: 'Run tests on all browsers (not just Chromium)'
        required: false
        type: boolean
        default: false

jobs:
  e2e:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.x
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Install Playwright browsers
        # Only install Chromium by default to speed up installation
        # Install all browsers if explicitly requested
        run: |
          if [ "${{ github.event.inputs.run_all_browsers }}" = "true" ]; then
            echo "Installing all browser engines..."
            pnpm playwright install --with-deps
          else
            echo "Installing Chromium only for faster CI..."
            pnpm playwright install --with-deps chromium
          fi
        
      - name: Run E2E tests
        run: pnpm playwright test
        env:
          NEXT_PUBLIC_FORMSPARK_FORM_ID: test-form-id
          # Set environment variable to run all browsers if specified
          RUN_ALL_BROWSERS: ${{ github.event.inputs.run_all_browsers == true && '1' || '0' }}
          
      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Upload Playwright failure artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-failures
          path: |
            test-results/
            playwright-report/
            test-results/debug-*.png
          retention-days: 30
          
      - name: Upload debug screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: debug-screenshots
          path: test-results/debug-*.png
          retention-days: 7