name: Generate Linux Visual Snapshots

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to generate snapshots for'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - chromium
          - firefox
          - webkit

jobs:
  generate-snapshots:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.x
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps
        
      - name: Generate snapshots
        run: |
          if [ "${{ github.event.inputs.browser }}" = "all" ]; then
            echo "Generating snapshots for all browsers"
            pnpm playwright test e2e/tests/splash-page-load.spec.ts --update-snapshots
          else
            echo "Generating snapshots for ${{ github.event.inputs.browser }}"
            pnpm playwright test e2e/tests/splash-page-load.spec.ts --update-snapshots --project=${{ github.event.inputs.browser }}
          fi
        env:
          NEXT_PUBLIC_FORMSPARK_FORM_ID: test-form-id
          
      - name: Upload snapshots as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-snapshots
          path: e2e/tests/splash-page-load.spec.ts-snapshots/
          retention-days: 7